// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-JrzLezoZmjUQBF0xtAv8I-5FJznPHcI',
    appId: '1:419674696351:web:915a90ef65214fa6bc10aa',
    messagingSenderId: '419674696351',
    projectId: 'jedar-center',
    authDomain: 'jedar-center.firebaseapp.com',
    storageBucket: 'jedar-center.firebasestorage.app',
    measurementId: 'G-ED5MMHGDSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgafEeLvdD18WHEOrDL0VIjZvHH7bWxcM',
    appId: '1:419674696351:android:30ed545320994208bc10aa',
    messagingSenderId: '419674696351',
    projectId: 'jedar-center',
    storageBucket: 'jedar-center.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-c-FbYxfzeD4dkDALli6icKaQet1lX7k',
    appId: '1:419674696351:ios:ab2f7d26219fa606bc10aa',
    messagingSenderId: '419674696351',
    projectId: 'jedar-center',
    storageBucket: 'jedar-center.firebasestorage.app',
    iosBundleId: 'jedarcenter.hadetha.hbh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-c-FbYxfzeD4dkDALli6icKaQet1lX7k',
    appId: '1:419674696351:ios:f91d4578b97fb081bc10aa',
    messagingSenderId: '419674696351',
    projectId: 'jedar-center',
    storageBucket: 'jedar-center.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-JrzLezoZmjUQBF0xtAv8I-5FJznPHcI',
    appId: '1:419674696351:web:db1c799d44046b10bc10aa',
    messagingSenderId: '419674696351',
    projectId: 'jedar-center',
    authDomain: 'jedar-center.firebaseapp.com',
    storageBucket: 'jedar-center.firebasestorage.app',
    measurementId: 'G-WXPC8YWSBS',
  );

}